import type { Metadata } from "next";
import { M_PLUS_Rounded_1c } from "next/font/google";
import Header from "@/components/header";
import "./globals.css";

export const mPlus = M_PLUS_Rounded_1c({
  weight: ["300", "400", "500"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${mPlus.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
